[package]
name = "rowops"
version = "0.1.0"
authors = ["Philippe R <philipper905@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.12"
termion = "1.5"